spring:
  datasource:
    url: postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: qqeNznIRsGBQeWnQQtWWoDYbssBaRqjq

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080